export enum ROLES {
  BASIC = 'BASIC',
  CREATOR = 'CREATOR',
  ADMIN = 'ADMIN',
}

export enum ACCESS_LEVEL {
  DEVELOPER = 30,
  MANTEINER = 40,
  OWNER = 50,
}

export enum STATUS_TASK {
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISH = 'FINISH',
}
